### ISSUE TITLE
Added a CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Botter#2]
> ## Description
> Create Contributors Guideline to help new Contributors get started with this Project.
> 
> ## Additional Details
> * Add a `CONTRIBUTING.md` to allow new users to get started with knowing how to contribute.
> * Add Screenshots wherever possible.
> * Add the basic information about creating Issues, Pull Requests and Branching.
> * Mention tutorials related to Git and Github to help them better understand.
> 
> You can use the content on the Notion Workspace as a reference for the Tutorial Links.

**Comment by ishikajn8126** [comment]
I would like to work on this issue. Plz assign this to me.

**Comment by Ayush7614** [comment]
Under which program @itsij

**Comment by ishikajn8126** [comment]
DevIncept 30 Day Contribution Program

**Comment by Ayush7614** [comment]
Okk Start working

**Comment by ishikajn8126** [comment]
is there any discord server or slack?

**Comment by Ayush7614** [comment]
> is there any discord server or slack?

Soon it is made by Devincept people
