### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Botter#3]
> ## Description
> Create a Code of Conduct which the Mentors and Participants must abide by.
> 
> ## Additional Details
> * Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
> * Add the required responsibilities for Project Maintainers.
> * Mention the Scope of this Code of Conduct.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me.
