### ISSUE TITLE
Added HTML Boilerplate 

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Botter#4]
Added HTML Boilerplate

**Comment by Baba-Yaga-1** [comment]
I am a participant of DevIncept, can I work on this issue ? Also could you mention what other elements should I insert in the html file.

**Comment by RakeshCharpe** [comment]
I would like to work on this issue under devIncept '21 .please assign to me

**Comment by RakeshCharpe** [comment]
Hi @Ayush7614  can you explain what actually I can do in it so I will work according to that.

**Comment by Ayush7614** [comment]
You can simply add HTML boilerplate that you can see in vscode
